# Generated by Django 4.1.7 on 2023-03-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='static_in_env/img/blog-post-1.jpeg', upload_to=''),
        ),
    ]
