# Generated by Django 4.1.7 on 2023-03-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='<h1>No Content Available</h1>'),
        ),
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=models.TextField(default=''),
        ),
    ]
