# Generated by Django 4.1.7 on 2023-03-05 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_next_post_post_previous_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
