# Generated by Django 4.1.7 on 2023-03-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_category_options_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='placeholder'),
            preserve_default=False,
        ),
    ]
